spring:
  application:
    name: api-gateway
server:
  port: 14000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
ribbon: 
  ReadTimeout: 120000  #请求处理的超时时间  
  ConnectTimeout: 30000  #请求连接的超时时间 
zuul:
  sensitiveHeaders: